version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: greys_postgres
    restart: always
    environment:
      POSTGRES_USER: greys
      POSTGRES_PASSWORD: greys_password
      POSTGRES_DB: greys_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
